spring.application.name=eng-rus
spring.thymeleaf.check-template-location=false
spring.value=Suka
spring.datasource.url=jdbc:postgresql://localhost:5432/translate
spring.datasource.username=postgres
spring.datasource.password=java2905